version: '3.8'

services:
  phone-app:
    image: darklordcoder/phone-app:latest
    container_name: phone-app-test
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    volumes:
      - sqlite-data:/app/data
    networks:
      - phone-network

networks:
  phone-network:
    name: phone-network
    driver: bridge

volumes:
  sqlite-data: 